FROM debian:stable AS builder

RUN apt-get update && apt-get install -y \
  build-essential \
  liblua5.4-dev \
  libtinyxml-dev \
  zlib1g-dev \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /opt
ADD http://www.ptokax.org/files/0.5.3.0-nix-src.tgz .
RUN tar zxvf 0.5.3.0-nix-src.tgz

WORKDIR /opt/PtokaX
RUN make

EXPOSE 1209
EXPOSE 411
VOLUME /config


CMD ["/opt/PtokaX/PtokaX", "-c", "/config"]
