services:
    test:
        build:
            dockerfile: ./tests/Dockerfile
        depends_on:
            - nmdc
        volumes:
            - .:/usr/src/app
    nmdc:
        build:
            dockerfile: ./tests/services/Dockerfile.nmdc
        ports:
            - "4111:411"
