on: push

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          curl -sSL https://install.python-poetry.org | python -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
          poetry install
          poetry run isort . --check-only
          poetry run mypy
          poetry run black . --check
          poetry run flake8
      - run: |
          poetry run coverage run -m pytest
          poetry run coverage report
